### ISSUE TITLE
German

### ISSUE THREAD

**Issue by Tlhey** [jma712/GEAR#2]
Hi, May I ask why __german__ dataset isn't used for calculating the counterfactual fairness subgraph and used for comparing the performance of node representation learning methods with respect to prediction and fairness?

**Comment by jma712** [comment]
> Hi, May I ask why **german** dataset isn't used for calculating the counterfactual fairness subgraph and used for comparing the performance of node representation learning methods with respect to prediction and fairness?

The original experiments did not include german, but it would be fine to try this dataset with our method as well.
